ROLE_TAXONOMY: dict[str, str] = {
    # ── Structure / Bulk ──
    "flour": "structure",
    "flours": "structure",
    "bread flour": "structure",
    "bread flours": "structure",
    "cake flour": "structure",
    "cake flours": "structure",
    "all-purpose": "structure",
    "whole wheat": "structure",
    "cornmeal": "structure",
    "cornmeals": "structure",
    "oat": "structure",
    "oats": "structure",
    "rice": "structure",
    "rices": "structure",
    "pasta": "structure",
    "pastas": "structure",
    "noodle": "structure",
    "noodles": "structure",
    "potato": "structure",
    "potatoes": "structure",
    "bread": "structure",
    "breads": "structure",
    "breadcrumb": "structure",
    "breadcrumbs": "structure",

    "cornstarch": "thickener",
    "arrowroot": "thickener",
    "tapioca": "thickener",
    "starch": "thickener",
    "starches": "thickener",
    "gelatin": "thickener",
    "pectin": "thickener",
    "agar": "thickener",
    "xanthan": "thickener",

    # ── Leavening ──
    "baking powder": "leavening",
    "baking powders": "leavening",
    "baking soda": "leavening",
    "yeast": "leavening",
    "yeasts": "leavening",
    "cream of tartar": "leavening",
    "sourdough": "leavening",

    # ── Fat ──
    "butter": "fat",
    "butters": "fat",
    "margarine": "fat",
    "shortening": "fat",
    "lard": "fat",
    "oil": "fat",
    "oils": "fat",
    "olive oil": "fat",
    "vegetable oil": "fat",
    "coconut oil": "fat",
    "sesame oil": "fat",
    "avocado oil": "fat",
    "cream": "fat",
    "creams": "fat",
    "heavy cream": "fat",
    "coconut cream": "fat",
    "sour cream": "fat",
    "crème fraîche": "fat",
    "ghee": "fat",
    "avocado": "fat",
    "avocados": "fat",
    "tahini": "fat",

    # ── Protein ──
    "egg": "protein",
    "eggs": "protein",
    "egg yolk": "protein",
    "egg yolks": "protein",
    "egg white": "protein",
    "egg whites": "protein",
    "chicken": "protein",
    "chickens": "protein",
    "beef": "protein",
    "pork": "protein",
    "lamb": "protein",
    "turkey": "protein",
    "turkeys": "protein",
    "salmon": "protein",
    "tuna": "protein",
    "shrimp": "protein",
    "tofu": "protein",
    "tempeh": "protein",
    "seitan": "protein",
    "chickpea": "protein",
    "chickpeas": "protein",
    "lentil": "protein",
    "lentils": "protein",
    "bean": "protein",
    "beans": "protein",
    "edamame": "protein",
    "cheese": "protein",
    "cheeses": "protein",
    "ricotta": "protein",
    "cottage cheese": "protein",

    # ── Liquid / Moisture ──
    "water": "liquid",
    "waters": "liquid",
    "milk": "liquid",
    "milks": "liquid",
    "almond milk": "liquid",
    "oat milk": "liquid",
    "soy milk": "liquid",
    "coconut milk": "liquid",
    "buttermilk": "liquid",
    "broth": "liquid",
    "broths": "liquid",
    "stock": "liquid",
    "stocks": "liquid",
    "wine": "liquid",
    "wines": "liquid",
    "beer": "liquid",
    "beers": "liquid",
    "juice": "liquid",
    "juices": "liquid",
    "vinegar": "liquid",
    "vinegars": "liquid",
    "coffee": "liquid",
    "coffees": "liquid",
    "tea": "liquid",
    "teas": "liquid",

    # ── Sweetener ──
    "sugar": "sweetener",
    "sugars": "sweetener",
    "brown sugar": "sweetener",
    "powdered sugar": "sweetener",
    "honey": "sweetener",
    "maple syrup": "sweetener",
    "agave": "sweetener",
    "molasses": "sweetener",
    "corn syrup": "sweetener",
    "stevia": "sweetener",
    "erythritol": "sweetener",
    "monk fruit": "sweetener",
    "date": "sweetener",
    "dates": "sweetener",

    # ── Acid / Brightness ──
    "lemon": "acid",
    "lemons": "acid",
    "lime": "acid",
    "limes": "acid",
    "orange": "acid",
    "oranges": "acid",
    "tomato": "acid",
    "tomatoes": "acid",
    "yogurt": "acid",
    "yogurts": "acid",
    "cream of tartar": "acid",
    "miso": "acid",
    "tamarind": "acid",

    # ── Seasoning / Flavor ──
    "salt": "seasoning",
    "salts": "seasoning",
    "pepper": "seasoning",
    "peppers": "seasoning",
    "garlic": "aromatic",
    "garlics": "aromatic",
    "onion": "aromatic",
    "onions": "aromatic",
    "shallot": "aromatic",
    "shallots": "aromatic",
    "leek": "aromatic",
    "leeks": "aromatic",
    "ginger": "aromatic",
    "scallion": "aromatic",
    "scallions": "aromatic",
    "chive": "aromatic",
    "chives": "aromatic",
    "celery": "aromatic",
    "fennel": "aromatic",

    "basil": "herb",
    "parsley": "herb",
    "cilantro": "herb",
    "thyme": "herb",
    "rosemary": "herb",
    "oregano": "herb",
    "sage": "herb",
    "dill": "herb",
    "mint": "herb",
    "bay leaf": "herb",
    "bay leaves": "herb",

    "cumin": "spice",
    "coriander": "spice",
    "paprika": "spice",
    "turmeric": "spice",
    "cinnamon": "spice",
    "nutmeg": "spice",
    "clove": "spice",
    "cloves": "spice",
    "cardamom": "spice",
    "cayenne": "spice",
    "chili": "spice",
    "chilies": "spice",
    "chilis": "spice",
    "curry": "spice",
    "allspice": "spice",

    "vanilla": "flavoring",
    "chocolate": "flavoring",
    "cocoa": "flavoring",
    "soy sauce": "flavoring",
    "fish sauce": "flavoring",
    "worcestershire": "flavoring",
    "hot sauce": "flavoring",
    "mustard": "flavoring",
    "ketchup": "flavoring",
    "anchovy": "flavoring",
    "anchovies": "flavoring",

    # ── Vegetable ──
    "carrot": "vegetable",
    "carrots": "vegetable",
    "broccoli": "vegetable",
    "cauliflower": "vegetable",
    "spinach": "vegetable",
    "kale": "vegetable",
    "cabbage": "vegetable",
    "cabbages": "vegetable",
    "zucchini": "vegetable",
    "zucchinis": "vegetable",
    "eggplant": "vegetable",
    "eggplants": "vegetable",
    "mushroom": "vegetable",
    "mushrooms": "vegetable",
    "bell pepper": "vegetable",
    "bell peppers": "vegetable",
    "corn": "vegetable",
    "pea": "vegetable",
    "peas": "vegetable",
    "asparagus": "vegetable",
    "artichoke": "vegetable",
    "artichokes": "vegetable",
    "beet": "vegetable",
    "beets": "vegetable",
    "radish": "vegetable",
    "radishes": "vegetable",
    "turnip": "vegetable",
    "turnips": "vegetable",

    # ── Fruit ──
    "apple": "fruit",
    "apples": "fruit",
    "banana": "fruit",
    "bananas": "fruit",
    "berry": "fruit",
    "berries": "fruit",
    "strawberry": "fruit",
    "strawberries": "fruit",
    "blueberry": "fruit",
    "blueberries": "fruit",
    "raspberry": "fruit",
    "raspberries": "fruit",
    "mango": "fruit",
    "mangoes": "fruit",
    "mangos": "fruit",
    "peach": "fruit",
    "peaches": "fruit",
    "pear": "fruit",
    "pears": "fruit",
    "cherry": "fruit",
    "cherries": "fruit",
    "grape": "fruit",
    "grapes": "fruit",
    "pineapple": "fruit",
    "pineapples": "fruit",
    "watermelon": "fruit",
    "watermelons": "fruit",

    # ── Nut / Seed ──
    "almond": "nut",
    "almonds": "nut",
    "walnut": "nut",
    "walnuts": "nut",
    "pecan": "nut",
    "pecans": "nut",
    "cashew": "nut",
    "cashews": "nut",
    "peanut": "nut",
    "peanuts": "nut",
    "pistachio": "nut",
    "pistachios": "nut",
    "hazelnut": "nut",
    "hazelnuts": "nut",

    "sesame": "seed",
    "chia": "seed",
    "flax": "seed",
    "sunflower seed": "seed",
    "sunflower seeds": "seed",
    "pumpkin seed": "seed",
    "pumpkin seeds": "seed",

    # ── Emulsifier ──
    "lecithin": "emulsifier",
    "mayonnaise": "emulsifier",
    "mustard": "emulsifier",

    # ── Coating / Crust ──
    "panko": "coating",
    "breadcrumbs": "coating",
    "flour": "coating",
    "flours": "coating",
}