# Role taxonomy — maps ingredient keywords → functional role node in the graph
ROLE_TAXONOMY: dict[str, str] = {
    # ── Structure / Bulk ──
    "flour": "structure",
    "bread flour": "structure",
    "cake flour": "structure",
    "all-purpose": "structure",
    "whole wheat": "structure",
    "cornmeal": "structure",
    "oat": "structure",
    "oats": "structure",
    "rice": "structure",
    "pasta": "structure",
    "noodle": "structure",
    "potato": "structure",
    "bread": "structure",
    "breadcrumb": "structure",
    "cornstarch": "thickener",
    "arrowroot": "thickener",
    "tapioca": "thickener",
    "starch": "thickener",
    "gelatin": "thickener",
    "pectin": "thickener",
    "agar": "thickener",
    "xanthan": "thickener",

    # ── Leavening ──
    "baking powder": "leavening",
    "baking soda": "leavening",
    "yeast": "leavening",
    "cream of tartar": "leavening",
    "sourdough": "leavening",

    # ── Fat ──
    "butter": "fat",
    "margarine": "fat",
    "shortening": "fat",
    "lard": "fat",
    "oil": "fat",
    "olive oil": "fat",
    "vegetable oil": "fat",
    "coconut oil": "fat",
    "sesame oil": "fat",
    "avocado oil": "fat",
    "cream": "fat",
    "heavy cream": "fat",
    "coconut cream": "fat",
    "sour cream": "fat",
    "crème fraîche": "fat",
    "ghee": "fat",
    "avocado": "fat",
    "tahini": "fat",

    # ── Protein ──
    "egg": "protein",
    "eggs": "protein",
    "egg yolk": "protein",
    "egg white": "protein",
    "chicken": "protein",
    "beef": "protein",
    "pork": "protein",
    "lamb": "protein",
    "turkey": "protein",
    "salmon": "protein",
    "tuna": "protein",
    "shrimp": "protein",
    "tofu": "protein",
    "tempeh": "protein",
    "seitan": "protein",
    "chickpea": "protein",
    "lentil": "protein",
    "bean": "protein",
    "edamame": "protein",
    "cheese": "protein",
    "ricotta": "protein",
    "cottage cheese": "protein",

    # ── Liquid / Moisture ──
    "water": "liquid",
    "milk": "liquid",
    "almond milk": "liquid",
    "oat milk": "liquid",
    "soy milk": "liquid",
    "coconut milk": "liquid",
    "buttermilk": "liquid",
    "broth": "liquid",
    "stock": "liquid",
    "wine": "liquid",
    "beer": "liquid",
    "juice": "liquid",
    "vinegar": "liquid",
    "coffee": "liquid",
    "tea": "liquid",

    # ── Sweetener ──
    "sugar": "sweetener",
    "brown sugar": "sweetener",
    "powdered sugar": "sweetener",
    "honey": "sweetener",
    "maple syrup": "sweetener",
    "agave": "sweetener",
    "molasses": "sweetener",
    "corn syrup": "sweetener",
    "stevia": "sweetener",
    "erythritol": "sweetener",
    "monk fruit": "sweetener",
    "date": "sweetener",

    # ── Acid / Brightness ──
    "lemon": "acid",
    "lime": "acid",
    "orange": "acid",
    "tomato": "acid",
    "yogurt": "acid",
    "cream of tartar": "acid",
    "miso": "acid",
    "tamarind": "acid",

    # ── Seasoning / Flavor ──
    "salt": "seasoning",
    "pepper": "seasoning",
    "garlic": "aromatic",
    "onion": "aromatic",
    "shallot": "aromatic",
    "leek": "aromatic",
    "ginger": "aromatic",
    "scallion": "aromatic",
    "chive": "aromatic",
    "celery": "aromatic",
    "fennel": "aromatic",
    "basil": "herb",
    "parsley": "herb",
    "cilantro": "herb",
    "thyme": "herb",
    "rosemary": "herb",
    "oregano": "herb",
    "sage": "herb",
    "dill": "herb",
    "mint": "herb",
    "bay leaf": "herb",
    "cumin": "spice",
    "coriander": "spice",
    "paprika": "spice",
    "turmeric": "spice",
    "cinnamon": "spice",
    "nutmeg": "spice",
    "clove": "spice",
    "cardamom": "spice",
    "cayenne": "spice",
    "chili": "spice",
    "curry": "spice",
    "allspice": "spice",
    "vanilla": "flavoring",
    "chocolate": "flavoring",
    "cocoa": "flavoring",
    "soy sauce": "flavoring",
    "fish sauce": "flavoring",
    "worcestershire": "flavoring",
    "hot sauce": "flavoring",
    "mustard": "flavoring",
    "ketchup": "flavoring",
    "anchovy": "flavoring",

    # ── Vegetable (bulk/texture) ──
    "carrot": "vegetable",
    "broccoli": "vegetable",
    "cauliflower": "vegetable",
    "spinach": "vegetable",
    "kale": "vegetable",
    "cabbage": "vegetable",
    "zucchini": "vegetable",
    "eggplant": "vegetable",
    "mushroom": "vegetable",
    "bell pepper": "vegetable",
    "corn": "vegetable",
    "pea": "vegetable",
    "asparagus": "vegetable",
    "artichoke": "vegetable",
    "beet": "vegetable",
    "radish": "vegetable",
    "turnip": "vegetable",

    # ── Fruit ──
    "apple": "fruit",
    "banana": "fruit",
    "berry": "fruit",
    "strawberry": "fruit",
    "blueberry": "fruit",
    "raspberry": "fruit",
    "mango": "fruit",
    "peach": "fruit",
    "pear": "fruit",
    "cherry": "fruit",
    "grape": "fruit",
    "pineapple": "fruit",
    "watermelon": "fruit",

    # ── Nut / Seed ──
    "almond": "nut",
    "walnut": "nut",
    "pecan": "nut",
    "cashew": "nut",
    "peanut": "nut",
    "pistachio": "nut",
    "hazelnut": "nut",
    "sesame": "seed",
    "chia": "seed",
    "flax": "seed",
    "sunflower seed": "seed",
    "pumpkin seed": "seed",

    # ── Emulsifier ──
    "lecithin": "emulsifier",
    "mayonnaise": "emulsifier",
    "mustard": "emulsifier",  # also flavoring — first match wins

    # ── Coating / Crust ──
    "panko": "coating",
    "breadcrumbs": "coating",
    "flour": "coating",  # duplicate - graph handles multiple roles
}
